CREATE TABLE IF NOT EXISTS users (
                                     id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name varchar(120) NOT NULL,
                                     email varchar(120) NOT NULL,
                                     UNIQUE(email)
);

CREATE TABLE IF NOT EXISTS categories (
                                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        name varchar(120)
);

CREATE TABLE IF NOT EXISTS events (
                                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        title varchar(120),
                                        description varchar(7000),
                                        annotation varchar(2000),
                                        status varchar(100),
                                        category_id int REFERENCES categories (id),
                                        createdOn TIMESTAMP,
                                        eventDate TIMESTAMP,
                                        publishedOn TIMESTAMP,
                                        location_id bigint,
                                        initiator_id bigint REFERENCES users (id),
                                        paid boolean,
                                        participantLimit int,
                                        requestModeration boolean
);

CREATE TABLE IF NOT EXISTS compilations (
                                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        title varchar(120),
                                        pinned boolean
);

CREATE TABLE IF NOT EXISTS compilations_events (
                                            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            compilation_id bigint REFERENCES compilations (id),
                                            event_id bigint REFERENCES events (id)
);

CREATE TABLE IF NOT EXISTS participation_request (
                                            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            created TIMESTAMP,
                                            pinned boolean,
                                            event_id bigint REFERENCES events (id),
                                            requester_id bigint REFERENCES users (id),
                                            status varchar(100)
);

CREATE TABLE IF NOT EXISTS location (
                                                     id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                     event_id bigint REFERENCES events (id),
                                                     lat float,
                                                     lon float
);
