CREATE TABLE IF NOT EXISTS hits
(
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app     varchar(200) NOT NULL,
    uri     varchar(200) NOT NULL,
    ip      varchar(50),
    created timestamp
);
