version: '3.1'
services:
  stats-server:
    build: stats-server/stats-server-client
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_db
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ewm_db

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    environment:
      - POSTGRES_PASSWORD=denden
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ewm_db


  ewm-service:
    build: ewm-service/
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
    environment:
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine