version: '3.8'
services:
  stats-server:
    build: stats-server/stats-server-service
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=denden

  stats-db:
    image: postgres:14-alpine
    container_name: ewm_stats_db
    restart: always
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_stats_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=denden
    volumes:
      - /var/lib/postgresql/data/

  ewm-service:
    build: ewm-service/
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-service-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-service-db:5432/ewm_main_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=denden

  ewm-service-db:
    image: postgres:14-alpine
    container_name: ewm_main_db
    restart: always
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm_main_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=denden
    volumes:
      - /var/lib/postgresql/data/