version: '3.1'
services:
  stats-server:
    build: stats-server/
    container_name: stats-server
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine

  ewm-service:
    build: ewm-service/
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
    environment:
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine