version: '3.1'
services:
  stats-server:
    build: stats-server/stats-server-client
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_db
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ewm_db

  stats-db:
    image: postgres:14-alpine
    container_name: ewm_stats_db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=denden
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ewm_stats_db


  ewm-service:
    build: ewm-service/
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-main-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_main_db
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ewm_main_db

  ewm-main-db:
    image: postgres:14-alpine
    container_name: ewm_main_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=denden
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ewm_main_db